import Head from 'next/head'
import { useState } from 'react';
import { useSelector } from 'react-redux'
import MatchGame from '../components/MatchGame';

export default function Home() {

  const [startGame, setStartGame] = useState(false);

  console.log("Index---");

  return (
    <div className="bg-gray-800 flex items-center justify-center h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='text-center'>
        <h1 className='text-white p-6 text-4xl font-bold'>Matching Game</h1>

        {startGame === false ?
          <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" onClick={() => { setStartGame(p => !p) }}>Start the game</button> :
          <MatchGame reset={setStartGame} />}

      </main>
    </div>
  )
}
